CREATE TABLE Blog(
  BlogId NUMBER(20) PRIMARY KEY NOT NULL,
  BlogName VARCHAR2(40) NOT NULL,
  UserId NUMBER(20) NOT NULL,
  CreateDate DATE DEFAULT (SYSDATE),
  BlogContent VARCHAR2(255),
  Likes NUMBER(20)
);


CREATE TABLE BlogComment(
  BlogCommentId NUMBER(20) PRIMARY KEY NOT NULL,
  BlogId NUMBER(20),
  UserId NUMBER(20),
  Username VARCHAR2(40),
  CommentDate DATE DEFAULT (SYSDATE),
  BlogComment VARCHAR2(255) NOT NULL
  
);

CREATE TABLE Forum(
  ForumId NUMBER(20) PRIMARY KEY NOT NULL,
  ForumName VARCHAR2(40) NOT NULL,
  UserId NUMBER(20) NOT NULL,
  CreateDate DATE DEFAULT (SYSDATE),
  ForumContent VARCHAR2(255)
);


CREATE TABLE ForumComment(
  ForumCommentId NUMBER(20) PRIMARY KEY NOT NULL,
  ForumId NUMBER(20),
  UserId NUMBER(20),
  Username VARCHAR2(40),
  CommentDate DATE DEFAULT (SYSDATE),
  ForumComment VARCHAR2(255) NOT NULL
  
);


CREATE TABLE Friend(
  UserId NUMBER(20) NOT NULL,
  FriendId NUMBER(20) NOT NULL,
  Status VARCHAR2(255)
);

CREATE TABLE Job(
  JobId NUMBER(20) PRIMARY KEY NOT NULL,
  JobProfile VARCHAR2(255) NOT NULL,
  JobDesc VARCHAR2(255) NOT NULL,
  Qualification VARCHAR2(255) NOT NULL,
  Status VARCHAR2(255) NOT NULL,
  PostDate  DATE DEFAULT (SYSDATE)
);

CREATE TABLE UserTable(
  UserId NUMBER(20) PRIMARY KEY NOT NULL,
  FirstName VARCHAR2(40) NOT NULL,
  LastName VARCHAR2(40) NOT NULL,
  Password VARCHAR2(40) NOT NULL,
  Email VARCHAR2(40) NOT NULL,
  Role VARCHAR2(40) NOT NULL,
  Status VARCHAR2(40) NOT NULL,
  IsOnline VARCHAR2(40) NOT NULL
 
);



